# Dockerfile to execute Node 2 Smart Mirror script with optional GPU support (CUDA 11.8)
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# ========================
# Copy components
# ========================
COPY env_config.json ./env_config.json
COPY shared-data/ ./shared-data/
COPY shared-data-tmp ./shared-data-tmp/
COPY opencv ./opencv/
COPY VITON-HD ./VITON-HD/
COPY run_only_viton.sh ./run_only_viton.sh

# ========================
# Instal dependencies
# ========================
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    jq \
    ca-certificates \
    curl \
    python3 \
    python3-distutils \
    python3-pip \
    python3-setuptools \
    git \
    && rm -rf /var/lib/apt/lists/*

# Update python
RUN python3 -m pip install --upgrade pip

# Install PyTorch
RUN pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu118

RUN pip install torchgeometry opencv-python-headless


# ========================
# Enable scripts
# ========================
RUN chmod +x run_only_viton.sh

# ========================
# Update env_config.json for Docker environment
# ========================
RUN jq '.MAIN_DIR="/app"' env_config.json > env_config_tmp.json && mv env_config_tmp.json env_config.json

# impostazioni opzionali
WORKDIR /app
